import Head from "next/head";
import dynamic from "next/dynamic";
import styles from "../styles/Home.module.css";
import React from "react";

const Button = dynamic(() => import("portal/button"), {
  ssr: true,
  suspense: true,
});

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>App1 - Hello from App 1!</h1>
        <React.Suspense fallback="loading button...">
          <Button />
        </React.Suspense>
      </main>
    </div>
  );
}

Home.getInitialProps = async () => ({});

export default Home;
